import type { Metadata } from "next";
import "./globals.css";

import { inter } from "./ui/fonts";

import { SideBarProvider } from "./providers/sidebar-provider";

export const metadata: Metadata = {
  title: "Financo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <SideBarProvider>{children}</SideBarProvider>
      </body>
    </html>
  );
}
